name: Execute Tests (develop)

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
      with: 
        submodules: recursive
        
    - name: Setup MsBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build Solution
      run: msbuild.exe .\BlindAid\BlindAid.sln /property:Configuration=Release /property:Platform=x64
      	
    - name: Setup Tests
      uses: darenm/Setup-VSTest@v1.1.1
    - name: Run Tests
      run: vstest.console.exe Blindaid/x64/Release/BlindAid.Test.dll
      	
    - name: Generate Artifacts
      uses: actions/upload-artifact@v2.2.1
      if: failure()
      with:
        name: "${{steps.vars.outputs.repo}}.${{steps.vars.outputs.branch}}.${{steps.vars.outputs.commit}}"
        paths: |
         Projects/BlindAid.Data/Result/*
         Projects/BlindAid.Data/Reference/*
         
